# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dmtree.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dmtree.proto',
  package='trpc.wecar_roi_s_app.wecar_roi_dmtree',
  syntax='proto3',
  serialized_options=b'\220\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x64mtree.proto\x12%trpc.wecar_roi_s_app.wecar_roi_dmtree\"\x16\n\x07ReqBody\x12\x0b\n\x03msg\x18\x01 \x01(\t\"$\n\x04Slot\x12\r\n\x05sname\x18\x01 \x01(\t\x12\r\n\x05stext\x18\x02 \x01(\t\"\x85\x01\n\x07RepBody\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x0e\n\x06intent\x18\x02 \x01(\t\x12:\n\x05slots\x18\x03 \x03(\x0b\x32+.trpc.wecar_roi_s_app.wecar_roi_dmtree.Slot\x12\x0e\n\x06status\x18\x04 \x01(\x05\x12\x0e\n\x06\x65rrmsg\x18\x05 \x01(\t2v\n\x06\x44Match\x12l\n\x08MatchStr\x12..trpc.wecar_roi_s_app.wecar_roi_dmtree.ReqBody\x1a..trpc.wecar_roi_s_app.wecar_roi_dmtree.RepBody\"\x00\x42\x03\x90\x01\x01\x62\x06proto3'
)




_REQBODY = _descriptor.Descriptor(
  name='ReqBody',
  full_name='trpc.wecar_roi_s_app.wecar_roi_dmtree.ReqBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='trpc.wecar_roi_s_app.wecar_roi_dmtree.ReqBody.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=77,
)


_SLOT = _descriptor.Descriptor(
  name='Slot',
  full_name='trpc.wecar_roi_s_app.wecar_roi_dmtree.Slot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sname', full_name='trpc.wecar_roi_s_app.wecar_roi_dmtree.Slot.sname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stext', full_name='trpc.wecar_roi_s_app.wecar_roi_dmtree.Slot.stext', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=115,
)


_REPBODY = _descriptor.Descriptor(
  name='RepBody',
  full_name='trpc.wecar_roi_s_app.wecar_roi_dmtree.RepBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='trpc.wecar_roi_s_app.wecar_roi_dmtree.RepBody.domain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intent', full_name='trpc.wecar_roi_s_app.wecar_roi_dmtree.RepBody.intent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='slots', full_name='trpc.wecar_roi_s_app.wecar_roi_dmtree.RepBody.slots', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='trpc.wecar_roi_s_app.wecar_roi_dmtree.RepBody.status', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errmsg', full_name='trpc.wecar_roi_s_app.wecar_roi_dmtree.RepBody.errmsg', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=251,
)

_REPBODY.fields_by_name['slots'].message_type = _SLOT
DESCRIPTOR.message_types_by_name['ReqBody'] = _REQBODY
DESCRIPTOR.message_types_by_name['Slot'] = _SLOT
DESCRIPTOR.message_types_by_name['RepBody'] = _REPBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqBody = _reflection.GeneratedProtocolMessageType('ReqBody', (_message.Message,), {
  'DESCRIPTOR' : _REQBODY,
  '__module__' : 'dmtree_pb2'
  # @@protoc_insertion_point(class_scope:trpc.wecar_roi_s_app.wecar_roi_dmtree.ReqBody)
  })
_sym_db.RegisterMessage(ReqBody)

Slot = _reflection.GeneratedProtocolMessageType('Slot', (_message.Message,), {
  'DESCRIPTOR' : _SLOT,
  '__module__' : 'dmtree_pb2'
  # @@protoc_insertion_point(class_scope:trpc.wecar_roi_s_app.wecar_roi_dmtree.Slot)
  })
_sym_db.RegisterMessage(Slot)

RepBody = _reflection.GeneratedProtocolMessageType('RepBody', (_message.Message,), {
  'DESCRIPTOR' : _REPBODY,
  '__module__' : 'dmtree_pb2'
  # @@protoc_insertion_point(class_scope:trpc.wecar_roi_s_app.wecar_roi_dmtree.RepBody)
  })
_sym_db.RegisterMessage(RepBody)


DESCRIPTOR._options = None

_DMATCH = _descriptor.ServiceDescriptor(
  name='DMatch',
  full_name='trpc.wecar_roi_s_app.wecar_roi_dmtree.DMatch',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=253,
  serialized_end=371,
  methods=[
  _descriptor.MethodDescriptor(
    name='MatchStr',
    full_name='trpc.wecar_roi_s_app.wecar_roi_dmtree.DMatch.MatchStr',
    index=0,
    containing_service=None,
    input_type=_REQBODY,
    output_type=_REPBODY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DMATCH)

DESCRIPTOR.services_by_name['DMatch'] = _DMATCH

DMatch = service_reflection.GeneratedServiceType('DMatch', (_service.Service,), dict(
  DESCRIPTOR = _DMATCH,
  __module__ = 'dmtree_pb2'
  ))

DMatch_Stub = service_reflection.GeneratedServiceStubType('DMatch_Stub', (DMatch,), dict(
  DESCRIPTOR = _DMATCH,
  __module__ = 'dmtree_pb2'
  ))


# @@protoc_insertion_point(module_scope)
